// AUTO-GENERATED by `ondajs add` — do not edit manually.
// Re-run `bunx ondajs add <slug>` to update.
// Pass `--no-barrel` to opt out; delete this file + .ondajs-installed.json
// to disable barrel management going forward.

import { AudioClip, audioClipSchema } from './audio-clip/AudioClip';
import { BlurReveal, blurRevealSchema } from './blur-reveal/BlurReveal';
import { BoundingBox, boundingBoxSchema } from './bounding-box/BoundingBox';
import { Callout, calloutSchema } from './callout/Callout';
import { CameraShake, cameraShakeSchema } from './camera-shake/CameraShake';
import { Captions, captionsSchema } from './captions/Captions';
import { ChapterCard, chapterCardSchema } from './chapter-card/ChapterCard';
import { CountUp, countUpSchema } from './count-up/CountUp';
import { Cursor, cursorSchema } from './cursor/Cursor';
import { DeviceFrame, deviceFrameSchema } from './device-frame/DeviceFrame';
import { EndCard, endCardSchema } from './end-card/EndCard';
import { FadeIn, fadeInSchema } from './fade-in/FadeIn';
import { GrainOverlay, grainOverlaySchema } from './grain-overlay/GrainOverlay';
import { Highlight, highlightSchema } from './highlight/Highlight';
import { IconPop, iconPopSchema } from './icon-pop/IconPop';
import { ImageReveal, imageRevealSchema } from './image-reveal/ImageReveal';
import { KenBurns, kenBurnsSchema } from './ken-burns/KenBurns';
import { MaskReveal, maskRevealSchema } from './mask-reveal/MaskReveal';
import { ProgressBar, progressBarSchema } from './progress-bar/ProgressBar';
import { ProgressSteps, progressStepsSchema } from './progress-steps/ProgressSteps';
import { QuoteCard, quoteCardSchema } from './quote-card/QuoteCard';
import { ScaleIn, scaleInSchema } from './scale-in/ScaleIn';
import { SlideIn, slideInSchema } from './slide-in/SlideIn';
import { SlotMachineRoll, slotMachineRollSchema } from './slot-machine-roll/SlotMachineRoll';
import { SplitScreen, splitScreenSchema } from './split-screen/SplitScreen';
import { Spotlight, spotlightSchema } from './spotlight/Spotlight';
import { StaggerGroup, staggerGroupSchema } from './stagger-group/StaggerGroup';
import { StatCard, statCardSchema } from './stat-card/StatCard';
import { TitleCard, titleCardSchema } from './title-card/TitleCard';
import { Underline, underlineSchema } from './underline/Underline';
import { VideoClip, videoClipSchema } from './video-clip/VideoClip';
import { Vignette, vignetteSchema } from './vignette/Vignette';
import { WordStagger, wordStaggerSchema } from './word-stagger/WordStagger';
import { blur, blurSchema } from './transitions/blur/blur';
import { crossFade, crossFadeSchema } from './transitions/cross-fade/crossFade';
import { depthPush, depthPushSchema } from './transitions/depth-push/depthPush';
import { dipToColor, dipToColorSchema } from './transitions/dip-to-color/dipToColor';
import { expandMorph, expandMorphSchema } from './transitions/expand-morph/expandMorph';
import { iris, irisSchema } from './transitions/iris/iris';
import { morph, morphSchema } from './transitions/morph/morph';
import { push, pushSchema } from './transitions/push/push';
import { slide, slideSchema } from './transitions/slide/slide';
import { wipe, wipeSchema } from './transitions/wipe/wipe';
import { zoom, zoomSchema } from './transitions/zoom/zoom';

export const ondaRegistry = {
  AudioClip: { component: AudioClip, schema: audioClipSchema },
  BlurReveal: { component: BlurReveal, schema: blurRevealSchema },
  BoundingBox: { component: BoundingBox, schema: boundingBoxSchema },
  Callout: { component: Callout, schema: calloutSchema },
  CameraShake: { component: CameraShake, schema: cameraShakeSchema },
  Captions: { component: Captions, schema: captionsSchema },
  ChapterCard: { component: ChapterCard, schema: chapterCardSchema },
  CountUp: { component: CountUp, schema: countUpSchema },
  Cursor: { component: Cursor, schema: cursorSchema },
  DeviceFrame: { component: DeviceFrame, schema: deviceFrameSchema },
  EndCard: { component: EndCard, schema: endCardSchema },
  FadeIn: { component: FadeIn, schema: fadeInSchema },
  GrainOverlay: { component: GrainOverlay, schema: grainOverlaySchema },
  Highlight: { component: Highlight, schema: highlightSchema },
  IconPop: { component: IconPop, schema: iconPopSchema },
  ImageReveal: { component: ImageReveal, schema: imageRevealSchema },
  KenBurns: { component: KenBurns, schema: kenBurnsSchema },
  MaskReveal: { component: MaskReveal, schema: maskRevealSchema },
  ProgressBar: { component: ProgressBar, schema: progressBarSchema },
  ProgressSteps: { component: ProgressSteps, schema: progressStepsSchema },
  QuoteCard: { component: QuoteCard, schema: quoteCardSchema },
  ScaleIn: { component: ScaleIn, schema: scaleInSchema },
  SlideIn: { component: SlideIn, schema: slideInSchema },
  SlotMachineRoll: { component: SlotMachineRoll, schema: slotMachineRollSchema },
  SplitScreen: { component: SplitScreen, schema: splitScreenSchema },
  Spotlight: { component: Spotlight, schema: spotlightSchema },
  StaggerGroup: { component: StaggerGroup, schema: staggerGroupSchema },
  StatCard: { component: StatCard, schema: statCardSchema },
  TitleCard: { component: TitleCard, schema: titleCardSchema },
  Underline: { component: Underline, schema: underlineSchema },
  VideoClip: { component: VideoClip, schema: videoClipSchema },
  Vignette: { component: Vignette, schema: vignetteSchema },
  WordStagger: { component: WordStagger, schema: wordStaggerSchema },
} as const;

export const ondaTransitions = {
  blur: { factory: blur, schema: blurSchema },
  crossFade: { factory: crossFade, schema: crossFadeSchema },
  depthPush: { factory: depthPush, schema: depthPushSchema },
  dipToColor: { factory: dipToColor, schema: dipToColorSchema },
  expandMorph: { factory: expandMorph, schema: expandMorphSchema },
  iris: { factory: iris, schema: irisSchema },
  morph: { factory: morph, schema: morphSchema },
  push: { factory: push, schema: pushSchema },
  slide: { factory: slide, schema: slideSchema },
  wipe: { factory: wipe, schema: wipeSchema },
  zoom: { factory: zoom, schema: zoomSchema },
} as const;
